version = 1

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = [
    "react",
    "angularjs",
    "angular",
    "vue",
    "ember",
    "meteor"
  ]

[[analyzers]]
name = "php"
enabled = true

[[transformers]]
name = "php-cs-fixer"
enabled = true